project_id = "kfsvpbujmetlendgwnrs"

[functions.generate-whatsapp-token]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false

[functions.send-announcement-email]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-stripe-portal]
verify_jwt = true

