[phases.setup]
nixPkgs = ['nodejs_21.1.0']

[phases.install]
cmds = ['export PATH="$PATH:./node_modules/.bin" && npm install']

[phases.build]
cmds = ['export PATH="$PATH:./node_modules/.bin" && npm run build']

[start]
cmd = 'npm run start'
